### ISSUE TITLE
Experiment on how many labeled datasets we need

### ISSUE THREAD

**Issue by RodrigoGuerra123** [DSEI21000-S21/project-mushroom-data-classification#4]

**Comment by mossnick** [comment]
Thinking 10 000? The more the better right? and our original set is like 8K so need at least that. But could do 25K thoughts?

**Comment by RodrigoGuerra123** [comment]
I think we should only produce a small percentage of the original dataset if we're going to build a semisupervised model. If we introduce too much of our own data it might bias the model and generalize too well

**Comment by mossnick** [comment]
What number are you thinking?

**Comment by RodrigoGuerra123** [comment]
Haven't looked into it but maybe something like 5% of 8K

**Comment by Imanjab** [comment]
Do you think having around 400 instances would be sufficient to conduct our algorithm?

**Comment by RodrigoGuerra123** [comment]
There are .csv files for 5, 50, and 100 samples per species on the Data Folder
