### ISSUE TITLE
Number of PCA to use in Clustering

### ISSUE THREAD

**Issue by mossnick** [DSEI21000-S21/project-mushroom-data-classification#5]
Ran Silhouette plots on the KMeans clustering for 2,3, and 40 PCA axis. The Silhouette coefficient ie score  ~0.33 for PCA2 and PCA3 for PCA40 it went to ~1.5. Looking like 40 Axes is too much as our score is going down. 

Going to run the other two clustering algorithms tomorrow and see what kind of separation we get.

**Comment by Imanjab** [comment]
How about we change the coefficient number that we're using. It looks like the elbow for the PCA is happening around the 15 threshold. It might make it somehow better if we use that value.
